name: cadastro_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  path_provider:
  sqflite_common_ffi:

flutter:
  uses-material-design: true
